// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBchhbf77EmaldggoEOUE1ZWX_qCFTVLCA',
    appId: '1:770946894742:android:7cc2b7e97d45d9e4876bb7',
    messagingSenderId: '770946894742',
    projectId: 'king-classes-13',
    storageBucket: 'king-classes-13.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBeJbFkxKrUTdMWZazTlHw150Ob7YR-oo',
    appId: '1:770946894742:ios:dd46b4e28f930302876bb7',
    messagingSenderId: '770946894742',
    projectId: 'king-classes-13',
    storageBucket: 'king-classes-13.firebasestorage.app',
    iosClientId: '770946894742-1khs1vktmofi0gk00o5udrnde7ltgrla.apps.googleusercontent.com',
    iosBundleId: 'org.khelafatmojlish.mojlishApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjhPTXjN4xg9w0_Is0s7ymn7dFWTbapE',
    appId: '1:770946894742:web:bbd229377aff2d86876bb7',
    messagingSenderId: '770946894742',
    projectId: 'king-classes-13',
    authDomain: 'king-classes-13.firebaseapp.com',
    storageBucket: 'king-classes-13.firebasestorage.app',
    measurementId: 'G-VNZS0SXT1L',
  );
}
